### ISSUE TITLE
Installazione in windows

### ISSUE THREAD

**Issue by wifi75** [alexucgit/gp-node#2]
CIao sto porvando ad instalarlo sotto windiows, ho installato l'ultima versione di node.js sia sul node-server che su greenpass reader appare il seguente errore dopo aver npm i:

![ERROR](https://user-images.githubusercontent.com/31816231/137276585-b9499978-f0cf-4520-b2f9-fc34e44f1bc4.PNG)

**Comment by wifi75** [comment]
ho provato anche su ubuntu server ma non funziona... il servizio non si avvia.

**Comment by alexucgit** [comment]
lancia node app.js

**Comment by wifi75** [comment]
> lancia node app.js

appare questo:
![image](https://user-images.githubusercontent.com/31816231/137321535-94bb0b50-53aa-45a1-9d79-168bbebc82de.png)

**Comment by wifi75** [comment]
però dopo il comando npm i ho i seguenti alert:
![image](https://user-images.githubusercontent.com/31816231/137322607-3981b203-f270-4482-81a6-3df3ff2431cf.png)

**Comment by alexucgit** [comment]
> 
> 
> > lancia node app.js
> 
> appare questo: ![image](https://user-images.githubusercontent.com/31816231/137321535-94bb0b50-53aa-45a1-9d79-168bbebc82de.png)

hai fatto npm install ?

**Comment by alexucgit** [comment]
> 
> 
> però dopo il comando npm i ho i seguenti alert: ![image](https://user-images.githubusercontent.com/31816231/137322607-3981b203-f270-4482-81a6-3df3ff2431cf.png)

sono warning che si possono correggere aggiornando le lib

**Comment by wifi75** [comment]
> > > lancia node app.js
> > 
> > 
> > appare questo: ![image](https://user-images.githubusercontent.com/31816231/137321535-94bb0b50-53aa-45a1-9d79-168bbebc82de.png)
> 
> hai fatto npm install ?

certo,  ogni volta che uso il node è un casotto... e me ne vado in crisi.. come posso aggiornare le librerie ? quale è il comendao?

**Comment by alexucgit** [comment]
> certo, ogni volta che uso il node è un casotto... e me ne vado in crisi.. come posso aggiornare le librerie ? quale è il comendao?

hai problemi di configurazione del node evidentemente.
solo il comando node cosa ti da?

**Comment by wifi75** [comment]
ho fatto un'installazione pulita di ubuntu server
solo il comando node mi da il prompt cosi; >

**Comment by wifi75** [comment]
Altrimenti su che distribuzione m conviene provare?

**Comment by alexucgit** [comment]
> 
> 
> ho fatto un'installazione pulita di ubuntu server solo il comando node mi da il prompt cosi; >

che versione di node?

**Comment by wifi75** [comment]
> > ho fatto un'installazione pulita di ubuntu server solo il comando node mi da il prompt cosi; >
> 
> che versione di node?

![image](https://user-images.githubusercontent.com/31816231/137325337-e3e5be76-cf9b-41af-90b2-0357906f6983.png)

**Comment by alexucgit** [comment]
> 
> 
> > > ho fatto un'installazione pulita di ubuntu server solo il comando node mi da il prompt cosi; >
> > 
> > 
> > che versione di node?
> 
> ![image](https://user-images.githubusercontent.com/31816231/137325337-e3e5be76-cf9b-41af-90b2-0357906f6983.png)

prova con la 14.
https://computingforgeeks.com/install-node-js-14-on-ubuntu-debian-linux/

**Comment by wifi75** [comment]
> > > > ho fatto un'installazione pulita di ubuntu server solo il comando node mi da il prompt cosi; >
> > > 
> > > 
> > > che versione di node?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/31816231/137325337-e3e5be76-cf9b-41af-90b2-0357906f6983.png)
> 
> prova con la 14. https://computingforgeeks.com/install-node-js-14-on-ubuntu-debian-linux/

un passo avanti:
![image](https://user-images.githubusercontent.com/31816231/137326695-3e6f39e2-237c-48df-9aee-da64622c41e9.png)

**Comment by alexucgit** [comment]
> un passo avanti: ![image](https://user-images.githubusercontent.com/31816231/137326695-3e6f39e2-237c-48df-9aee-da64622c41e9.png)

ok, funziona.

**Comment by wifi75** [comment]
adesso ho aperto un'altra sessione ed sto scaricando le dipendenze di greenpass-reader non trovo il file  environment da editare, dove inserire l'ip del pc...
